services:
  traefik:
    container_name: traefik
    image: traefik:v3.6
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565"
    volumes:
      - ./static.yml:/etc/traefik/static.yml:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certificates:/certificates
    environment:
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
networks:
  traefik:
    external: true
volumes:
  certificates:
